
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80
# ---
apiVersion: v1
kind: Service
metadata:
  name: testapp
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: testapp
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: testapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp
        image: docker.io/1mihirpandya/testapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {duration: 5s}
      - setWeight: 50
      - pause: {duration: 5s}
      - setWeight: 75
      - pause: {duration: 5s}
      - setWeight: 100
